openapi: 3.0.1
info:
  title: VisitorStats
  description: API Definition of VisitorStats
  version: 1.0.0
servers:
- url: http://localhost:8290/visitorstats
paths:
  /:
    get:
      responses:
        default:
          description: Default response
